### PR TITLE
fix  _TensorParallelMappingForHuggingFace error

### LINKED ISSUE #88: No _TensorParallelMappingForHuggingFace
## How to reproduce

```python 
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nnodes=1 --nproc_per_node=2  ./tests/torch/nn/parallel/data_parallel/test_ddp.py
```
The bus comes from latest submission which changes _TensorParallelMappingForHuggingFace to _ParallelMapping. It happens when parallel_context is called. (tensor_parallel import issue)

## Environment

- OS : 18.04
- Python version : 3.7
- Transformers version : 4.21.2
- Whether to use Docker:
- Misc.:

### PR DESCRIPTION
**Pull request by dongsungkim**
## Title
There is a bug after changing _TensorParallelMappingForHuggingFace to _ParallelMapping in oslo/oslo/transformers/mapping_utils.py

## Description
Changed _wrapper.py in tensor_parallel to sync with the previous submission. (No _TensorParallelMappingForHuggingFace found error)

## Linked Issues

- resolved #88

### CODE REVIEW

**Comment by dongsungkim** [comment]
confirmed by James as well

**Comment by hyunwoongko** [comment]
Good !

**Comment by josemlopez** [comment]
Hi, 
When running the test I continue seeing the same error: 


`
$ python -m torch.distributed.run --nproc_per_node=2 --master_port=2333 test_fsdp.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "test_fsdp.py", line 11, in <module>
Traceback (most recent call last):
  File "test_fsdp.py", line 11, in <module>
    from oslo.torch.distributed import ParallelContext
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/__init__.py", line 2, in <module>
    from oslo.torch.distributed import ParallelContext
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/__init__.py", line 2, in <module>
    from oslo.torch.utils.extensions import ready_torch
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/utils/extensions.py", line 14, in <module>
    from oslo.torch.utils.extensions import ready_torch
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/utils/extensions.py", line 14, in <module>
    from oslo.torch.nn.parallel.pipeline_parallel.pipeline_parallel import (
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/__init__.py", line 4, in <module>
    from oslo.torch.nn.parallel.pipeline_parallel.pipeline_parallel import (
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/__init__.py", line 4, in <module>
    from oslo.torch.nn.parallel.tensor_parallel import *
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/tensor_parallel/__init__.py", line 2, in <module>
    from oslo.torch.nn.parallel.tensor_parallel import *
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/tensor_parallel/__init__.py", line 2, in <module>
    from oslo.torch.nn.parallel.tensor_parallel.tensor_parallel import TensorParallel
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/tensor_parallel/tensor_parallel.py", line 8, in <module>
    from oslo.torch.nn.parallel.tensor_parallel.tensor_parallel import TensorParallel
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/tensor_parallel/tensor_parallel.py", line 8, in <module>
    from oslo.torch.nn.parallel.tensor_parallel._1d._wrapper import (
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/tensor_parallel/_1d/_wrapper.py", line 31, in <module>
    from oslo.torch.nn.parallel.tensor_parallel._1d._wrapper import (
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/torch/nn/parallel/tensor_parallel/_1d/_wrapper.py", line 31, in <module>
    from oslo.transformers.mapping_utils import (
ImportError: cannot import name '_TensorParallelMappingForHuggingFace' from 'oslo.transformers.mapping_utils' (/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/transformers/mapping_utils.py)
    from oslo.transformers.mapping_utils import (
ImportError: cannot import name '_TensorParallelMappingForHuggingFace' from 'oslo.transformers.mapping_utils' (/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/oslo_core-3.0.0-py3.8.egg/oslo/transformers/mapping_utils.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 34456) of binary: /fsx/home-jlopez/miniconda3/envs/dev38/bin/python
Traceback (most recent call last):
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/fsx/home-jlopez/miniconda3/envs/dev38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
`
Could it be something in my side?

**Comment by dongsungkim** [comment]
hi @josemlopez 
I think you need to update main which it has a new mapping _TensorParallelMapping rather than _TensorParallelMappingForHuggingFace. oslo/transformers/mapping_utils.py looks like not being updated yet in your local directory.

Please let me know if you have any issue afterwards

**Comment by josemlopez** [comment]
Hi, 
Thanks, I did it.

**Pull request merged**
