### PR TITLE
Expert parallel

### PR DESCRIPTION
**Pull request by scsc0511**
## Title

- Expert Parallel Pull Request 

## Description

- Switch codebase from colossalai to deepspeed
- Implement Expert Parallel + Data Parallel 

## Linked Issues
[#4]

- resolved #00

### CODE REVIEW

**Comment by scsc0511** [comment]
I have merged main branch to expert parallel in local. 
So i think it is ok you just check and leave expert_parallel branch code 
or if you leave message that you have checked, i will do that

**Comment by hyunwoongko** [comment]
You need to modify only expert parallel related code.

**Comment by hyunwoongko** [comment]
there are 314 file changes and some conflicting files.
how about working like this?

1. clone latest code branch
2. modify only expert parallel related parts based on your current codebase
3. make pr

**Comment by hyunwoongko** [comment]
And you need to sync more frequently.
it will prevent some situations like this.

**Pull request closed without merging**
