### PR TITLE
[MOD] initialize when oslo config not setting

### PR DESCRIPTION
**Pull request by hmy831004**
## Title

- [Trainer] Oslo Config initialize

## Description

- inititialize when oslo config path or dict not setting 

##Checkpoint
- default word size not set when oslo_config not setting (2022.12.07)

- The default word size is set to "world_size = int(os.environ["WORLD_SIZE"])". Can I do this?  (2022.12.02)

### CODE REVIEW

**Comment by hyunwoongko** [comment]
@tree-park please review this

**Comment by tree-park** [comment]
Why do we need to redefine "WORLD_SIZE"?
Plus, default option should be "default" but it looks like it's DP.

**Comment by hmy831004** [comment]
It is intended to default to DP when the user does not specify parallel settingts in oslo config 
Is it correct that the parallel technique does not work when the user does not specify oslo config?
@tree-park

**Comment by tree-park** [comment]
My opinion is default option should be remain as nothing defined about parallels, what do you think @hyunwoongko ?

**Comment by hyunwoongko** [comment]
yes. as you said, default value of parallel context was also 0.
I think it would be better to no parallelism as default.

**Pull request closed without merging**
