### PR TITLE
[#82] implement deparallelization feature for expert_parallel

### LINKED ISSUE #82: TODO : Deparallelize expert parallel
## Describe a TODO feature

- Deparallelize the expert parallelized model

## Assignees

- scsc0511

### PR DESCRIPTION
**Pull request by scsc0511**
## Title

- Deparallelize expert parallel

## Description

- Implement features of deparallelization for expert parallel 

## Linked Issues

- resolved #82

### CODE REVIEW

**Comment by hyunwoongko** [comment]
good. I think it would be better to test with save_pretrained function.

**Comment by scsc0511** [comment]
I have thought that it is better to implement and test that feature for new issue because I have to implement ExpertParallel function (not _ExpertParallel) and it is more clear to implement it with another issue. But if you think that it is better to test with save_pretrained, I will do that.

**Comment by hyunwoongko** [comment]
that is also good. I will merge it now. thanks

**Comment by scsc0511** [comment]
Thanks for your help

**Pull request merged**
