### PR TITLE
[Fix] zero optimizer w/ tensor parallel test

### PR DESCRIPTION
**Pull request by yhna940**
## Title

- [Fix] zero optimizer w/ tensor parallel test

## Description

- ZeRO was not running in tensor parallel mode, so I fixed this by switching to a model from `transformers`.

## Linked Issues

- N/A

### CODE REVIEW

**Comment by KKIEEK** [comment]
I think uou need to invoke [parallelize](https://github.com/EleutherAI/oslo/blob/master/oslo/torch/nn/parallel/utils.py#L59) function or oslo.ready for TensorParallel.

**Comment by hyunwoongko** [comment]
You don't need to move full model to GPU.
Just use `oslo.ready(model, pc)`.

**Comment by yhna940** [comment]
> Unfortunately, it still doesn't work because of [these line](https://github.com/EleutherAI/oslo/blob/main/oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/_utils.py#L38-L40).
> 
> ```shell
> E       torch.multiprocessing.spawn.ProcessRaisedException: 
> E       
> E       -- Process 0 terminated with the following error:
> E       Traceback (most recent call last):
> E         File "/admin/home/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
> E           fn(i, *args)
> E         File "/admin/home/vit/tests_deprecated/torch/nn/parallel/data_parallel/zero/test_hybrid.py", line 103, in run_dist
> E           run(parallel_context)
> E         File "/admin/home/vit/tests_deprecated/torch/nn/parallel/data_parallel/zero/test_hybrid.py", line 89, in run
> E           hybrid_optimizer.step()
> E         File "/admin/home/vit/oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/sharded_optim.py", line 581, in step
> E           norm_group = compute_norm(
> E         File "/admin/home/vit/oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/_utils.py", line 230, in compute_norm
> E           if is_model_parallel_parameter(p) or mp_rank == 0:
> E         File "/admin/home/vit/oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/_utils.py", line 39, in is_model_parallel_parameter
> E           return ParallelMode.PIPELINE in parallel_mode or any(
> E         File "/admin/home/vit/oslo/torch/nn/parallel/data_parallel/zero/sharded_optim/_utils.py", line 40, in <genexpr>
> E           key.startswith("tensor") for key in parallel_mode
> E       AttributeError: 'ParallelMode' object has no attribute 'startswith'
> ```
> 
>  ```shell
> >>> from oslo.torch.distributed import ParallelMode
> >>> ParallelMode.TENSOR_1D.startswith('tensor')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'ParallelMode' object has no attribute 'startswith'
> ```

There was a small bug and it was fixed.
https://github.com/EleutherAI/oslo/pull/164/files

**Review by KKIEEK — APPROVED** [review]

**Review by l4d2boomer — COMMENTED** [review]
👍

**Pull request merged**
