### PR TITLE
Feature/84 apply vocab parallel cross entropy

### PR DESCRIPTION
**Pull request by loopinf**
## Title
- Add test of vocab parallel 

## Description

- found bugs regarding checking oslo model and fix
- Fix pytorch inline operation error by A --> A.clone()
- 

## Linked Issues

- resolved #108

### CODE REVIEW

**Comment by loopinf** [comment]
there is a bug on 3d vocabparallel

**Comment by hyunwoongko** [comment]
What bug did you find?

**Comment by loopinf** [comment]
> What bug did you find?

```
File "/fsx/loopinf/oslo-1/oslo/transformers/models/gpt2/modeling_gpt2.py", line 370, in forward

  File "/fsx/loopinf/venv/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/loopinf/oslo-1/oslo/transformers/models/gpt2/modeling_gpt2.py", line 370, in forward
    attn_output, attn_bias = self.c_proj(attn_output)
ValueError: too many values to unpack (expected 2)
    return forward_call(*input, **kwargs)
```

**Comment by hyunwoongko** [comment]
How about discussing with me about this?
Are you free at Wednesday night?

**Comment by hyunwoongko** [comment]
Let's merge this for now. and I will make a new pr to fix bug in TP3D.
You don't need to care the bug. I will fix. thanks for opening great PR :)

**Pull request merged**
