### PR TITLE
[Enhance] Support ViT for TensorParallel

### PR DESCRIPTION
**Pull request by KKIEEK**
## Description

I added support for ViT in TensorParallel by appending config to `_TensorParallelMapping`.
`PatchEmbed` layer in ViT does not have the `weight` parameter unlike `Embedding` layer, so I replaced the `weight` parameter with a dummy value to prevent an `AttributeError`.

Any feedback is welcome.

### Memory usage
mode | world_size=1 | world_size=2 | world_size=4 | world_size=8
-|-|-|-|-
1D | 1760MiB | 1126MiB | 789MiB |
2D | | | 589MiB |
2.5D (d=1) | | | 589MiB |
2.5D (d=2) | | | | 586MiB
3D | | | |

### TODO
- [ ] Benchmark with `world_size=8`
- [ ] Refactor slicing patch embedding
- [ ] Fix slicing logic to return the same value as `TensorParallel1D`

<details><summary>code for testing</summary>
<p>

```python
import os
import torch.multiprocessing as mp

import torch
from torch import nn
from torch import optim
import torch.distributed as dist
from transformers import ViTModel, ViTForImageClassification, ViTConfig

import oslo
from oslo.torch.distributed.parallel_context import ParallelContext
from oslo.torch.distributed.parallel_mode import ParallelMode
from oslo.torch.nn.parallel import TensorParallel


def setup(rank, world_size):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "12340"
    os.environ["RANK"] = str(rank)
    os.environ["LOCAL_RANK"] = str(rank)
    os.environ["WORLD_SIZE"] = str(world_size)
    os.environ["LOCAL_WORLD_SIZE"] = str(world_size)


def cleanup():
    dist.destroy_process_group()


def train(rank, world_size):
    print(f"Running oslo TP example on rank {rank}.")
    setup(rank, world_size)
    parallel_context = ParallelContext.from_torch(
        tensor_parallel_size=world_size,
        tensor_parallel_mode=ParallelMode.TENSOR_1D,
    )  # TENSOR2D or TENSOR_2P5D

    model = ViTForImageClassification(ViTConfig(num_labels=1000)).to(rank)
    model = TensorParallel(model, parallel_context)
    optimizer = optim.SGD(model.parameters(), lr=1e-4)
    loss_fn = nn.MSELoss()

    oslo.ready(model, parallel_context)

    for _ in range(100):
        model.zero_grad()
        logits = model(pixel_values=torch.ones(8, 3, 224, 224).to(rank)).logits
        labels = torch.ones(8, 1000).to(rank) * 100
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()
        print(logits)
        print(torch.cuda.max_memory_allocated() / 1024**2)  # MB

    cleanup()


def main(world_size):
    mp.spawn(train, args=(world_size,), nprocs=world_size, join=True)


if __name__ == "__main__":
    main(4)
```

</p>
</details> 

## Linked Issues

Related to #152

### CODE REVIEW

**Comment by KKIEEK** [comment]
Currently, TensorParallel for ViT does not support TensorParallel greater than 1D.
Could anyone let me know why `LayerNorm` is not working with 2D and 2.5 TensorParallelism?
```
Traceback (most recent call last):
  File "/admin/home/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/admin/home/vit/test_tp.py", line 46, in train
    logits = model(pixel_values=torch.ones(8, 3, 224, 224).to(rank)).logits
  File "/admin/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/admin/home/vit/oslo/torch/nn/parallel/tensor_parallel/tensor_parallel.py", line 95, in forward
    return self.module_forward(*args, **kwargs)
  File "/admin/home/vit/oslo/torch/nn/parallel/tensor_parallel/_2p5d/_wrapper.py", line 71, in forward
    return self.module_forward(*args, **kwargs)
  File "/admin/home/.local/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 789, in forward
    outputs = self.vit(
  File "/admin/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/admin/home/.local/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 579, in forward
    encoder_outputs = self.encoder(
  File "/admin/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/admin/home/.local/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 409, in forward
    layer_outputs = layer_module(hidden_states, layer_head_mask, output_attentions)
  File "/admin/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/admin/home/.local/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 349, in forward
    self.layernorm_before(hidden_states),  # in ViT, layernorm is applied before self-attention
  File "/admin/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/admin/home/vit/oslo/torch/nn/modules/layer_norm.py", line 317, in forward
    outputs = torch.addcmul(bias, scale, outputs)
RuntimeError: The size of tensor a (384) must match the size of tensor b (768) at non-singleton dimension 2
```

**Comment by hyunwoongko** [comment]
I think there's something wrong config on ViT mapping.
@bzantium @jason9693 could you check it on thursday together?

**Comment by hyunwoongko** [comment]
@KKIEEK I suggest you to join model parallel team meeting on thursday. let's discuss together.

**Comment by KKIEEK** [comment]
@hyunwoongko Okay, I see.

**Comment by bzantium** [comment]
> I think there's something wrong config on ViT mapping.
> @bzantium @jason9693 could you check it on thursday together?

Sure! I will check

**Comment by hyunwoongko** [comment]
@KKIEEK please let me know when you are done :)

**Comment by KKIEEK** [comment]
@hyunwoongko 
I roughly have fixed the `ViTEmbeddings` to work well with 2D TensorParallelism, but I don't think this implementation is elegant in current TensorParallel scheme. Do you have any suggestions for improving it?

**Comment by KKIEEK** [comment]
@hyunwoongko Can you review this PR for me? If you don't get a chance to do, I will close this PR.

**Pull request merged**
