### PR TITLE
Apply Multi-head Attention Layer of LightSeq2 on BERT

### LINKED ISSUE #131: TODO: CUDA Kernel for Transformer Model

### PR DESCRIPTION
**Pull request by dyanos**
## Title

  - To apply Multi-head Attention Layer of LightSeq2 on BERT

## Description

- Add Kernel Code in LightSeq2 and Modify BERT to Use Multi-head Attention Layer

## Linked Issues

- resolved #131

### CODE REVIEW

**Comment by hyunwoongko** [comment]
@dyanos Could you run `pre-commit run --all-files` ?

**Comment by dyanos** [comment]
> @dyanos Could you run `pre-commit run --all-files` ?

@hyunwoongko 

It's currently in progress.

**Comment by dyanos** [comment]
@hyunwoongko 

Pre-commit passed.
The following two files are directly related to learning. Please review the following two codes.

oslo/lightseq2/training/ops/pytorch/multihead_attention_layer.py
oslo/transformers/models/bert/modeling_bert.py

**Comment by hyunwoongko** [comment]
LGTM

**Pull request merged**
